apiVersion: v1
kind: Service
metadata:
  name: salody-svc 
  namespace: salody
spec:
  clusterIP: 10.96.1.4
  type: NodePort
  ports:
  - port: 80
    nodePort: 30004
    targetPort: 80
  selector:
    module: salody
    app: salody-service 
