apiVersion: v1
kind: Service
metadata:
  name: blog-svc 
  namespace: blog
spec:
  clusterIP: 10.96.1.2
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 80
  selector:
    module: blog
    app: blog-service 
