apiVersion: v1
kind: Service
metadata:
  name: mysql-svc 
  namespace: mysql
spec:
  clusterIP: 10.96.1.3
  type: NodePort
  ports:
  - port: 3306
    nodePort: 30002
    targetPort: 3306
  selector:
    module: db
    app: mysql 
